language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
script: python -m projmon.test
notifications:
  webhooks: http://project-monitor.cf.18f.us/projects/project-monitor/status
